In [0]:
import tensorflow as tf

In [0]:
mnist = tf.keras.datasets.mnist

In [5]:
type(mnist)

module

In [6]:
(x_train,y_train),(x_test, y_test) = mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [7]:
x_train.shape

(60000, 28, 28)

In [8]:
 y_train.shape

(60000,)

In [9]:
x_test.shape

(10000, 28, 28)

In [10]:
y_test.shape

(10000,)

In [11]:
60000/255

235.2941176470588

In [0]:
x_train, x_test = x_train/255.0 , x_test/255.0

In [0]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [0]:
pred = model(x_train[:1]).numpy()

In [24]:
tf.nn.softmax(pred).numpy()

array([[0.09995753, 0.1000159 , 0.1000168 , 0.10003515, 0.10016619,
        0.10017998, 0.10005445, 0.09997077, 0.09968215, 0.09992104]],
      dtype=float32)

In [0]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)


In [28]:
loss_fn(y_train[:1], pred).numpy()

2.300787

In [0]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [30]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 1.1998 - accuracy: 0.7084
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.5309 - accuracy: 0.8552
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.4202 - accuracy: 0.8818
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3695 - accuracy: 0.8940
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3391 - accuracy: 0.9013


In [31]:
model.evaluate(x_test,  y_test, verbose=2)


313/313 - 0s - loss: 0.2906 - accuracy: 0.9171


[0.29061159491539, 0.9171000123023987]

In [0]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [33]:
probability_model(x_test[:5])


<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.33467955e-04, 1.72048047e-07, 1.00240773e-04, 1.24976784e-03,
        1.27578699e-06, 9.38119992e-05, 7.00263314e-09, 9.95753527e-01,
        2.84618272e-05, 2.63921032e-03],
       [3.46577470e-03, 4.30374057e-05, 9.48846519e-01, 2.17340440e-02,
        9.80262627e-09, 1.19475704e-02, 5.66893956e-03, 1.57512581e-08,
        8.29403196e-03, 3.76956137e-08],
       [1.13736169e-05, 9.76708472e-01, 7.71760289e-03, 4.02505510e-03,
        2.70075223e-04, 1.90762640e-03, 1.78707950e-03, 3.89930373e-03,
        2.93939072e-03, 7.33975321e-04],
       [9.97543871e-01, 3.86847943e-10, 4.02929611e-04, 1.09954308e-04,
        3.04772357e-07, 1.55775365e-03, 1.27348438e-04, 1.07471875e-04,
        8.89414368e-05, 6.13949087e-05],
       [7.12659443e-04, 1.39641224e-05, 6.25865906e-03, 1.84883727e-04,
        9.00436342e-01, 3.62453028e-03, 3.70876049e-03, 9.38359369e-03,
        3.81009746e-03, 7.18666017e-02]], dtype=float32)>